// Static data for facilities - replaces Firebase for static deployment

// Treatment Center Data
window.STATIC_FACILITIES_DATA = [
    {
        id: 1,
        name: "Revive Inc Horizon Recovery and Counseling Center",
        type: "Treatment Center",
        address: "2205 Osborne Drive East, Suite 115, Hastings, NE 68901",
        phone: "402-462-2066",
        website: "http://www.reviveinc.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.6089061, lng: -98.3835624 }
    },
    {
        id: 2,
        name: "Mid Plains Center for Behavioral Healthcare Services Inc",
        type: "Treatment Center",
        address: "914 Baumann Drive, Grand Island, NE 68803",
        phone: "308-385-5250",
        website: "http://www.midplainscenter.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.9270149, lng: -98.3634847 }
    },
    {
        id: 3,
        name: "CenterPointe Adult Long Term Residential Program",
        type: "Treatment Center",
        address: "2220 South 10th Street, Lincoln, NE 68502",
        phone: "402-475-8748",
        website: "http://www.centerpointe.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7905172, lng: -96.7062497 }
    },
    {
        id: 4,
        name: "CenterPointe Adult Long Term Residential Program",
        type: "Treatment Center",
        address: "2220 South 10th Street, Lincoln, NE 68502",
        phone: "402-475-8748",
        website: "http://www.centerpointe.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7905172, lng: -96.7062497 }
    },
    {
        id: 5,
        name: "CenterPointe Campus for Health and WellBeing",
        type: "Treatment Center",
        address: "2202 South 11th Street, Lincoln, NE 68502",
        phone: "402-475-5161",
        website: "http://www.centerpointe.org/",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7906329, lng: -96.7050452 }
    },
    {
        id: 6,
        name: "Bridge Behavioral Health",
        type: "Treatment Center",
        address: "721 K Street, Lincoln, NE 68508",
        phone: "402-477-3951",
        website: "http://",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.8088716, lng: -96.7108461 }
    },
    {
        id: 7,
        name: "Bridge Behavioral Health",
        type: "Treatment Center",
        address: "721 K Street, Lincoln, NE 68508",
        phone: "402-477-3951",
        website: "http://www.thebridgenebraska.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.8088716, lng: -96.7108461 }
    },
    {
        id: 8,
        name: "Saint Monicas Behavioral Health Servs Women Are Sacred",
        type: "Treatment Center",
        address: "1100 Military Road, Lincoln, NE 68508",
        phone: "402-441-3768",
        website: "http://www.stmonicas.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.8310343, lng: -96.7050537 }
    },
    {
        id: 9,
        name: "Saint Monicas Behavioral Health Servs Project Mother and Child",
        type: "Treatment Center",
        address: "1100 Military Road, Lincoln, NE 68508",
        phone: "402-441-3768",
        website: "http://www.stmonicas.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.8310343, lng: -96.7050537 }
    },
    {
        id: 10,
        name: "Houses of Hope of Nebraska Inc Halfway House",
        type: "Treatment Center",
        address: "1124 North Cotner Boulevard, Lincoln, NE 68505",
        phone: "402-435-3165 x112",
        website: "http://www.housesofhope.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.8242072, lng: -96.6328112 }
    },
    {
        id: 11,
        name: "Whitehall Program",
        type: "Treatment Center",
        address: "5900 Walker Avenue, Lincoln, NE 68507",
        phone: "402-471-6969",
        website: "http://",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.8369741, lng: -96.639674 }
    },
    {
        id: 12,
        name: "Saint Monicas Affirming Womens Empowerment",
        type: "Treatment Center",
        address: "105 Wedgewood Drive, Lincoln, NE 68510",
        phone: "402-441-3768",
        website: "http://www.stmonicas.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.8125387, lng: -96.6233429 }
    },
    {
        id: 13,
        name: "Saint Monicas Behavioral Health Servs Short Term Residential",
        type: "Treatment Center",
        address: "120 Wedgewood Drive, Lincoln, NE 68510",
        phone: "402-441-3768",
        website: "http://www.stmonicas.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.8123341, lng: -96.6225218 }
    },
    {
        id: 14,
        name: "Saint Monicas Behavioral Health Servs Therapeutic Community",
        type: "Treatment Center",
        address: "120 Skyway Drive, Lincoln, NE 68510",
        phone: "402-441-3768",
        website: "http://www.stmonicas.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.81398, lng: -96.6157804 }
    },
    {
        id: 15,
        name: "Behavioral Health Specialists Inc Seekers for Serenity",
        type: "Treatment Center",
        address: "4432 Sunrise Place, Columbus, NE 68601",
        phone: "402-564-9994",
        website: "http://",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.4295473, lng: -97.3814131 }
    },
    {
        id: 16,
        name: "Behavioral Health Specialists Inc Seekers of Serenity Place",
        type: "Treatment Center",
        address: "4432 Sunrise Place, Columbus, NE 68601",
        phone: "402-564-9994",
        website: "http://www.4bhs.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.4295473, lng: -97.3814131 }
    },
    {
        id: 17,
        name: "Community Alliance",
        type: "Treatment Center",
        address: "7150 Arbor Street, Omaha, NE 68106",
        phone: "402-341-5128",
        website: "https://community-alliance.org/",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.236914, lng: -96.0230252 }
    },
    {
        id: 18,
        name: "Community Alliance Orchard House",
        type: "Treatment Center",
        address: "Omaha, NE 68117",
        phone: "402-341-5128",
        website: "http://community-alliance.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.2074, lng: -95.996 }
    },
    {
        id: 19,
        name: "Community Alliance Cole Creek",
        type: "Treatment Center",
        address: "Omaha, NE 68134",
        phone: "402-341-5128",
        website: "http://community-alliance.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.2952, lng: -96.0546 }
    },
    {
        id: 20,
        name: "Community Alliance Arbor House",
        type: "Treatment Center",
        address: "Omaha, NE 68106",
        phone: "402-341-5128",
        website: "http://community-alliance.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.2389, lng: -96.0014 }
    },
    {
        id: 21,
        name: "Community Alliance Alliance House",
        type: "Treatment Center",
        address: "Omaha, NE 68106",
        phone: "402-341-5128",
        website: "http://community-alliance.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.2389, lng: -96.0014 }
    },
    {
        id: 22,
        name: "Inroads to Recovery Inc",
        type: "Treatment Center",
        address: "2808 North 75th Street, Omaha, NE 68134",
        phone: "402-932-2248",
        website: "http://inroadstorecovery.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.2842075, lng: -96.0283009 }
    },
    {
        id: 23,
        name: "Stephen Center Inc",
        type: "Treatment Center",
        address: "5217 South 28th Street, Omaha, NE 68107",
        phone: "402-715-5449",
        website: "http://www.stephencenter.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.2048342, lng: -95.9544201 }
    },
    {
        id: 24,
        name: "Stephen Center Inc",
        type: "Treatment Center",
        address: "5217 South 28th Street, Omaha, NE 68107",
        phone: "402-715-5449",
        website: "http://www.stephencenter.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.204818, lng: -95.954323 }
    },
    {
        id: 25,
        name: "Nebraska Urban Indian Health Coalition Intertribal Treatment Center",
        type: "Treatment Center",
        address: "2226 North Street, Omaha, NE 68107",
        phone: "402-346-0902 x202",
        website: "http://www.nuihc.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.2099802, lng: -95.9453188 }
    },
    {
        id: 26,
        name: "Nebraska Urban Indian Health Coalition Intertribal Treatment Center",
        type: "Treatment Center",
        address: "2226 North Street, Omaha, NE 68107",
        phone: "402-346-0902 x202",
        website: "http://www.nuihc.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.2099802, lng: -95.9453188 }
    }
];

// Halfway Houses Data
window.STATIC_HALFWAY_HOUSES_DATA = [
    {
        id: 27,
        name: "VA Nebraska/Western Iowa HCS Grand Island CBOC",
        type: "Halfway House",
        address: "2201 North Broadwell Avenue, Grand Island, NE 68803",
        phone: "402-995-4473 x2134",
        website: "http://www.nebraska.va.gov/locations/Grand_Island.asp",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 28,
        name: "Friendship House Inc",
        type: "Halfway House",
        address: "406 West Koenig Street, Grand Island, NE 68801",
        phone: "308-675-3345 x18",
        website: "http://www.thefriendshiphouse.net",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 29,
        name: "Revive Inc Horizon Recovery and Counseling Center",
        type: "Halfway House",
        address: "2205 Osborne Drive East, Suite 115, Hastings, NE 68901",
        phone: "402-462-2066",
        website: "http://www.reviveinc.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 30,
        name: "Womens Empowering Life Line Inc Intermediate Residential",
        type: "Halfway House",
        address: "200 South 13th Street, Norfolk, NE 68701",
        phone: "402-860-8483",
        website: "http://www.womenslifeline.net",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 31,
        name: "The Link Inc",
        type: "Halfway House",
        address: "1001 West Norfolk Avenue, Norfolk, NE 68701",
        phone: "402-371-5310",
        website: "http://link-recovery.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 32,
        name: "Human Services Inc",
        type: "Halfway House",
        address: "419 West 25th Street, Alliance, NE 69301",
        phone: "308-762-7177",
        website: "http://www.hsinc.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 33,
        name: "Houses of Hope of Nebraska Inc Halfway House",
        type: "Halfway House",
        address: "1124 North Cotner Boulevard, Lincoln, NE 68505",
        phone: "402-435-3165 x112",
        website: "http://www.housesofhope.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 34,
        name: "Saint Monicas Affirming Womens Empowerment",
        type: "Halfway House",
        address: "105 Wedgewood Drive, Lincoln, NE 68510",
        phone: "402-441-3768",
        website: "http://www.stmonicas.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 35,
        name: "ARCH Inc OHanlon House",
        type: "Halfway House",
        address: "1502 North 58th Street, Omaha, NE 68104",
        phone: "402-556-6425",
        website: "http://www.archhalfwayhouse.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 36,
        name: "Heartland Family Service",
        type: "Halfway House",
        address: "4847 Sahler Street, Omaha, NE 68104",
        phone: "402-342-9555",
        website: "http://www.heartlandfamilyservice.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 37,
        name: "Santa Monica Inc",
        type: "Halfway House",
        address: "401 South 39th Street, Omaha, NE 68131",
        phone: "402-558-7088",
        website: "http://www.santamonicahouse.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 38,
        name: "ARCH Inc",
        type: "Halfway House",
        address: "604 South 37th Street, Omaha, NE 68105",
        phone: "402-346-8898",
        website: "http://www.archhalfwayhouse.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 39,
        name: "Stephen Center Inc",
        type: "Halfway House",
        address: "5217 South 28th Street, Omaha, NE 68107",
        phone: "402-715-5449",
        website: "http://www.stephencenter.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    },
    {
        id: 40,
        name: "Open Door Missions Mens Ministries",
        type: "Halfway House",
        address: "2705 North 20th Street East, Omaha, NE 68110",
        phone: "402-422-1111",
        website: "http://www.opendoormission.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 0.0, lng: 0.0 }
    }
];

// Outpatient Services Data
window.STATIC_OUTPATIENT_DATA = [
    {
        id: 41,
        name: "Lexington Regional Health Center",
        type: "Outpatient",
        address: "1201 North Erie Street, Lexington, NE 68850",
        phone: "308-324-5651",
        website: "http://www.lexingtonregional.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7858929, lng: -99.7589814 }
    },
    {
        id: 42,
        name: "Lexington Regional Health Center",
        type: "Outpatient",
        address: "1201 North Erie Street, Lexington, NE 68850",
        phone: "308-324-5651",
        website: "http://www.lexingtonregional.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7858929, lng: -99.7589814 }
    },
    {
        id: 43,
        name: "Lutheran Family Services of Nebraska Lexington",
        type: "Outpatient",
        address: "800 North Washington Street, Suite 2, Lexington, NE 68850",
        phone: "308-532-0587",
        website: "http://www.onelfs.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7812316, lng: -99.7409967 }
    },
    {
        id: 44,
        name: "Lutheran Family Services of Nebraska Lexington",
        type: "Outpatient",
        address: "800 North Washington Street, Suite 2, Lexington, NE 68850",
        phone: "308-532-0587",
        website: "http://www.onelfs.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7812316, lng: -99.7409967 }
    },
    {
        id: 45,
        name: "Heartland Counseling Clinic",
        type: "Outpatient",
        address: "307 East 5th Street, Lexington, NE 68850",
        phone: "308-324-6754",
        website: "http://www.r2hs.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7779918, lng: -99.7380302 }
    },
    {
        id: 46,
        name: "Heartland Counseling Clinic",
        type: "Outpatient",
        address: "307 East 5th Street, Lexington, NE 68850",
        phone: "308-324-6754",
        website: "http://www.r2hs.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7779918, lng: -99.7380302 }
    },
    {
        id: 47,
        name: "Valley County Health System Heritage Program for Seniors",
        type: "Outpatient",
        address: "110 South 26th Street, Ord, NE 68862",
        phone: "308-728-4340",
        website: "http://www.valleycountyhealthsystem.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.6031461, lng: -98.9413518 }
    },
    {
        id: 48,
        name: "Lutheran Family Services",
        type: "Outpatient",
        address: "120 East 12th Street, North Platte, NE 69101",
        phone: "308-532-0587",
        website: "http://www.onelfs.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Mental Health",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.1459158, lng: -100.7602155 }
    },
    {
        id: 49,
        name: "Lutheran Family Services",
        type: "Outpatient",
        address: "120 East 12th Street, North Platte, NE 69101",
        phone: "308-532-0587",
        website: "http://www.onelfs.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.1459158, lng: -100.7602155 }
    },
    {
        id: 50,
        name: "Psychiatric Hope",
        type: "Outpatient",
        address: "321 East 3rd Street, North Platte, NE 69101",
        phone: "308-520-7794",
        website: "http://www.psychiatrichope.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Substance Abuse",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.1353248, lng: -100.759992 }
    }
];

// Detox Services Data
window.STATIC_DETOX_DATA = [
    {
        id: 51,
        name: "Lexington Regional Health Center",
        type: "Detox",
        address: "1201 North Erie Street, Lexington, NE 68850",
        phone: "308-324-5651",
        website: "http://www.lexingtonregional.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7858929, lng: -99.7589814 }
    },
    {
        id: 52,
        name: "Psychiatric Hope",
        type: "Detox",
        address: "321 East 3rd Street, North Platte, NE 69101",
        phone: "308-221-4651",
        website: "http://www.psychiatrichope.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.1353248, lng: -100.759992 }
    },
    {
        id: 53,
        name: "Mid Plains Center for Behavioral Healthcare Services Inc",
        type: "Detox",
        address: "914 Baumann Drive, Grand Island, NE 68803",
        phone: "308-385-5250",
        website: "http://www.midplainscenter.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.9265447331352, lng: -98.3632822752136 }
    },
    {
        id: 54,
        name: "Valley Hope of ONeill",
        type: "Detox",
        address: "1421 North 10th Street, O'Neill, NE 68763",
        phone: "785-877-5111",
        website: "http://www.valleyhope.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 42.4694532, lng: -98.6393916 }
    },
    {
        id: 55,
        name: "Revive Inc Horizon Recovery and Counseling Center",
        type: "Detox",
        address: "2205 Osborne Drive East, Suite 115, Hastings, NE 68901",
        phone: "402-462-2066",
        website: "http://www.reviveinc.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.6089061, lng: -98.3835624 }
    },
    {
        id: 56,
        name: "Behavioral Health Specialists Inc Seekers of Serenity Place",
        type: "Detox",
        address: "4432 Sunrise Place, Columbus, NE 68601",
        phone: "402-564-9994",
        website: "http://www.4bhs.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.4295473, lng: -97.3814131 }
    },
    {
        id: 57,
        name: "Behavioral Health Specialists Inc Sunrise Place",
        type: "Detox",
        address: "1900 Vicki Lane, Norfolk, NE 68701",
        phone: "402-379-0040",
        website: "http://www.4bhs.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 42.0240841, lng: -97.435609 }
    },
    {
        id: 58,
        name: "Bridge Behavioral Health",
        type: "Detox",
        address: "721 K Street, Lincoln, NE 68508",
        phone: "402-477-3951",
        website: "http://www.thebridgenebraska.org",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.8088716, lng: -96.7108461 }
    },
    {
        id: 59,
        name: "Bryan Medical Center West Independence Center",
        type: "Detox",
        address: "1640 Lake Street, Lincoln, NE 68502",
        phone: "402-481-5268",
        website: "http://www.bryanhealth.com/services/alcohol-drug-treatment",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7884103, lng: -96.6980563 }
    },
    {
        id: 60,
        name: "Pine Lake Behavioral Health/Medical",
        type: "Detox",
        address: "9100 Andermatt Drive, Suite 1, Lincoln, NE 68526",
        phone: "402-434-2730 x1",
        website: "http://www.pinelakebh.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 40.7335633, lng: -96.5931464 }
    },
    {
        id: 61,
        name: "Nebraska Medical Center",
        type: "Detox",
        address: "4350 Dewey Avenue, Omaha, NE 68105",
        phone: "800-922-0000",
        website: "http://www.nebraskamed.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.2562523, lng: -95.9764351 }
    },
    {
        id: 62,
        name: "BAART Community Healthcare Inc",
        type: "Detox",
        address: "1941 South 42nd Street, Suite 210, Omaha, NE 68105",
        phone: "402-341-6220",
        website: "http://www.baartprograms.com",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.2406369, lng: -95.9750427 }
    },
    {
        id: 63,
        name: "Douglas County Mental Health Center",
        type: "Detox",
        address: "1490 North 16th Street, Omaha, NE 68102",
        phone: "402-444-1975",
        website: "http://cmhc.douglascounty-ne.gov",
        ageGroup: "Adult",
        genderServed: "Co-ed",
        treatmentType: "Detox",
        status: "Contact for Availability",
        lastUpdated: "2025-01-27",
        coordinates: { lat: 41.272717, lng: -95.9384233 }
    }
];

// Combined data for search functionality
window.STATIC_ALL_FACILITIES_DATA = [
    ...window.STATIC_FACILITIES_DATA,
    ...window.STATIC_HALFWAY_HOUSES_DATA,
    ...window.STATIC_OUTPATIENT_DATA,
    ...window.STATIC_DETOX_DATA
];

// Mock provider data for demo (if needed)
window.STATIC_PROVIDERS_DATA = [
    {
        id: "provider1",
        email: "provider1@example.com",
        name: "Provider One",
        facilities: [1, 2], // First two facilities
        isActive: true
    },
    {
        id: "provider2",
        email: "provider2@example.com",
        name: "Provider Two",
        facilities: [3, 4], // Next two facilities
        isActive: true
    }
];