# Netlify configuration for Nebraska Treatment Connect

[build]
  # No build process needed for static site
  publish = "."

[build.environment]
  # Environment variables can be set in Netlify dashboard

[[redirects]]
  # Redirect root to static version
  from = "/"
  to = "/index-static.html"
  status = 200

[[redirects]]
  # Handle 404s by serving the main page
  from = "/*"
  to = "/index-static.html"
  status = 404

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://maps.googleapis.com https://maps.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https://maps.googleapis.com https://maps.gstatic.com; connect-src 'self' https://maps.googleapis.com;"